In [2]:
import os 
from pathlib import Path 

if "notebooks" in os.getcwd():
    os.chdir("..")
%pwd


'/home/penguinsfly/Documents/playground/urban/uncertain-social-bandit'

In [3]:
import pandas as pd
import numpy as np
import xarray as xr
import numpy.random as npr
import copy

from tqdm import tqdm
from pathlib import Path

from itertools import product as iterprod

import socialbandit as sb


In [51]:
model = sb.models.SocialMultiArmedBandit(
    task_settings   = sb.tasks.ChildDevelopmentEnvironment(env_levels=12), 
    social_settings = sb.social.SocialSetting(N = 100, social_fn=None),
#     social_settings = sb.social.SocialSetting(N = 100, social_fn='all2all'),
#     social_settings = sb.social.SocialSetting(N = 100, social_fn=sb.social.Homophily(beta=-4.6)),
    clock           = sb.utils.ExperimentClock(T = 1000),
    initializer     = sb.initializers.InitializerBanditAgnostic(mu_fn=lambda x: 0.1*np.max(x)),
    action_sampler  = sb.tasks.SoftmaxSampler(tau = 1.0),
    belief_updater  = sb.beliefs.BayesianMeanTracker(),
    action_learner  = sb.learners.MeanGreedyExploit(),
#     action_learner  = sb.learners.UpperConfidenceBound(beta = 0.2),
    social_learner  = sb.learners.SocialMassPower(alpha = 0.8)
)

model.set_state_managers()
model.run()
model.states.to_xarray()

model.states.Yc.sum()

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 624.39it/s]


4049988.8609728506

In [29]:

4109826
2756924
3949797
3840001
4019814

array([53.29402292, 54.01129208, 42.13270134,  7.94990927, 51.96123079,
        7.63891032, 27.10410478, 41.55450735,  7.22250117,  4.86938852,
       26.78323047, 55.9024213 ,  1.73093773, 23.88532307, 28.6911497 ,
       26.76570827, 52.24705363, 20.82607519,  5.26171844, 24.99850497,
       28.1040603 , 27.17980505, -0.        ,  8.83786631, 53.89170761,
       46.71936521, 40.95544324, 28.74762579,  2.0611429 ,  2.24620149,
        4.94988189, 25.29545091,  8.95851364, 45.20190697, 26.34696731,
       45.35222704, 11.49872937, 45.76479175, 22.76153511, 48.84459227,
       48.42271667, 41.3801892 , 45.53515568,  7.68241168, 51.50611499,
       44.23902615, 44.89347375, 29.2213838 , 49.2354667 , 39.06794817,
       28.85963532, 56.46047168, 46.37856531, 21.09011991, 42.23831436,
       34.10517733, 44.8058921 ,  8.83493432, 46.70535904, 44.98527316,
       40.27806944, 46.75023395, 19.94151359, 22.093816  , 28.73574908,
        7.64487239,  9.64568257,  9.6399874 , 45.32234817,  8.48

In [10]:
print(model.t)
model.step()
model.states.M

1


array([[100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.],
       ...,
       [100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.],
       [100., 100., 100., ..., 100., 100., 100.]])

In [6]:
task_settings = sb.tasks.ChildDevelopmentEnvironment(), 
model = sb.models.SocialMultiArmedBandit(
    task_settings   = sb.tasks.ChildDevelopmentEnvironment(), 
    social_settings = sb.social.SocialSetting(N=10, social_fn=None),
    clock           = sb.utils.ExperimentClock(T = 100),
    initializer     = None, # default to optimistic priors with equal probs
    action_sampler  = sb.tasks.SoftmaxSampler(tau = 1.0),
    belief_updater  = sb.beliefs.BayesianMeanTracker(var_error = 1.0),
    action_learner  = sb.learners.MeanGreedyExploit(),
    social_learner  = sb.learners.SocialMassPower(alpha = 0.8)
)


array([46.5639473 , 44.05670346, 43.16884312, 48.19070889, 47.85518732,
       47.51096617, 46.01663042, 45.39572396, 45.71012223, 44.68876043])

In [51]:
model.task_settings[96]

{'mean': 45.45454545454547, 'var': 1.0}

In [78]:
np.where(model.states.A)

(array([96, 96, 96, 96, 96, 96, 96, 96, 97, 97]),
 array([1, 2, 3, 4, 5, 6, 7, 9, 0, 8]))

In [77]:
model.states.V

array([[40.5, 40.5, 40.5, ..., 40.5, 40.5, 40.5],
       [40.5, 40.5, 40.5, ..., 40.5, 40.5, 40.5],
       [40.5, 40.5, 40.5, ..., 40.5, 40.5, 40.5],
       ...,
       [40.5, 40.5, 40.5, ..., 40.5, 40.5, 40.5],
       [40.5, 40.5, 40.5, ..., 40.5, 40.5, 40.5],
       [40.5, 40.5, 40.5, ..., 40.5, 40.5, 40.5]])

In [16]:
model.sample_action()

In [25]:
model.sample_reward()

In [33]:
model.update_belief()

In [34]:
model.states.G.sum(axis=0)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [ ]:
model.run()

model.states.to_xarray()

In [55]:
model = sb.models.SocialMultiArmedBandit(
    task_settings   = sb.tasks.ChildDevelopmentEnvironment(), 
    social_settings = sb.social.SocialSetting(N=10, social_fn=None),
    clock           = sb.utils.ExperimentClock(T = 1000),
    initializer     = None, # default to optimistic priors with equal probs
    action_sampler  = sb.tasks.SoftmaxSampler(tau = 1.0),
    belief_updater  = sb.beliefs.BayesianMeanTracker(var_error = 1.0),
    action_learner  = sb.learners.UpperConfidenceBound(beta = 0.1),
    social_learner  = sb.learners.SocialMassPower(alpha = 0.8)
)

model.set_state_managers()
model.run()

model.states.to_xarray()


100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 2702.91it/s]


<xarray.Dataset>
Dimensions:  (t: 1, task: 144, agent: 10, neighbor: 10, _: 1)
Coordinates:
  * t        (t) int64 1001
Dimensions without coordinates: task, agent, neighbor, _
Data variables: (12/13)
    Q_sol    (t, task, agent) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    W        (t, neighbor, agent) float64 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    Q_acl    (t, task, agent) float64 -95.79 -97.55 -94.14 ... 91.33 88.6 91.78
    M        (t, task, agent) float64 -95.79 -97.55 -94.14 ... 91.33 88.6 91.78
    G        (t, task, agent) float64 0.9877 0.9877 0.9877 ... 0.9937 0.9968
    Yc       (t, task, agent) float64 -100.6 -102.4 -98.93 ... 91.12 205.9 299.7
    ...       ...
    A        (t, task, agent) bool False False False False ... False False False
    rho      (t, task, _) float64 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0
    V        (t, task, agent) float64 80.02 80.02 80.02 ... 80.02 158.1 316.2
    Y        (t, task, agent) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    C        (t, task, agent) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    Q        (t, task, agent) float64 -95.79 -97.55 -94.14 ... 91.33 88.6 91.78
Attributes:
    state_desc:  {'t': {'name': 't', 'type': 'dim'}, 'K': {'name': 'number of...

In [56]:
np.where(model.states.A)

(array([132, 132, 132, 132, 132, 132, 132, 132, 132, 133]),
 array([0, 2, 3, 4, 5, 6, 7, 8, 9, 1]))

In [74]:
model.states.Y.max(axis=0)

array([100.20645634,  98.92404399,  98.66983237, 100.38495049,
       100.74495033,  99.22150655,  98.65159216, 100.21239317,
        99.7274717 , 101.54678935, 100.11809141, 100.87530785,
       101.21728611, 100.54579335, 101.3722365 , 100.12466372,
       100.80652229,  98.6041597 , 100.08805898, 100.21664954,
        98.55484076,  99.54074337,  98.82229629,  99.68256853,
        99.85992754,  99.84403716, 100.65275506,  97.98486283,
        99.19619599, 100.28406777, 100.5299527 ,  99.67607241,
        99.65701708, 101.5592277 , 100.41607872,  99.7279973 ,
       100.22743014,  98.84661301, 100.08826144,  99.65123059,
       100.94358253,  99.39106926,  99.07627017, 100.62084333,
       100.94517655, 100.55850153, 100.19964249, 101.05115426,
       101.16838149, 100.80940022,  97.89839645,  99.83057661,
        99.99889632,  99.67865071,  99.02697316,  99.85961568,
        99.9694552 ,  99.46387955, 101.68251671,  99.59032727,
        99.34213576,  99.51573911, 100.27880257, 100.16

In [73]:
model = sb.models.SocialMultiArmedBandit(
    task_settings   = sb.tasks.ChildDevelopmentEnvironment(), 
    social_settings = sb.social.SocialSetting(N=100, social_fn=sb.social.Homophily(beta=1.0)),
    clock           = sb.utils.ExperimentClock(T = 1000),
    initializer     = None, # default to optimistic priors with equal probs
    action_sampler  = sb.tasks.SoftmaxSampler(tau = 1.0),
    belief_updater  = sb.beliefs.BayesianMeanTracker(var_error = 1.0),
    action_learner  = sb.learners.MeanGreedyExploit(),
    social_learner  = sb.learners.SocialMassPower(alpha = 1.0)
)

model.set_state_managers()
model.run()


  0%|                                                  | 0/1000 [00:00<?, ?it/s]/home/penguinsfly/Documents/playground/urban/uncertain-social-bandit/socialbandit/social.py:117: RuntimeWarning: divide by zero encountered in power
  X = np.power(sim_mat, self.beta) # like similarity^{beta}
/home/penguinsfly/Documents/playground/urban/uncertain-social-bandit/socialbandit/utils.py:7: RuntimeWarning: invalid value encountered in true_divide
  return X / np.sum(X, axis=0, keepdims=True)
100%|██████████████████████████████████████| 1000/1000 [00:03<00:00, 254.43it/s]


In [63]:

model.states.to_xarray()

<xarray.Dataset>
Dimensions:  (t: 1, task: 144, agent: 100, neighbor: 100, _: 1)
Coordinates:
  * t        (t) int64 101
Dimensions without coordinates: task, agent, neighbor, _
Data variables: (12/13)
    Q_sol    (t, task, agent) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    W        (t, neighbor, agent) float64 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 1.0
    Q_acl    (t, task, agent) float64 100.0 100.0 100.0 ... 100.0 100.0 100.0
    M        (t, task, agent) float64 100.0 100.0 100.0 ... 100.0 100.0 100.0
    G        (t, task, agent) float64 0.9759 0.9759 0.9759 ... 0.9759 0.9759
    Yc       (t, task, agent) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    ...       ...
    A        (t, task, agent) bool False False False False ... False False False
    rho      (t, task, _) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    V        (t, task, agent) float64 40.5 40.5 40.5 40.5 ... 40.5 40.5 40.5
    Y        (t, task, agent) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    C        (t, task, agent) bool False False False False ... False False False
    Q        (t, task, agent) float64 100.0 100.0 100.0 ... 100.0 100.0 100.0
Attributes:
    state_desc:  {'t': {'name': 't', 'type': 'dim'}, 'K': {'name': 'number of...

In [5]:
model = sb.models.SocialMultiArmedBandit(
    task_settings   = sb.tasks.ChildDevelopmentEnvironment(), 
    social_settings = sb.social.SocialSetting(N=4,social_fn=None),
    clock           = sb.utils.ExperimentClock(T = 1000),
    initializer     = None, # default to optimistic priors with equal probs
    action_sampler  = sb.tasks.SoftmaxSampler(tau = 1.0),
    belief_updater  = sb.beliefs.BayesianMeanTracker(var_error = 1.0),
    action_learner  = sb.learners.MeanGreedyExploit(),
    social_learner  = None
)

model.set_state_managers()
model.run()

100%|██████████████████| 1000/1000 [00:00<00:00, 3258.43it/s]
